global:
  resolve_timeout: 5m
  # Configure these for your environment
  # smtp_smarthost: 'smtp.example.com:587'
  # smtp_from: 'alerts@example.com'
  # smtp_auth_username: 'alerts@example.com'
  # smtp_auth_password: 'password'
  # smtp_require_tls: true
  # slack_api_url: 'https://hooks.slack.com/services/TXXXXXXXX/BXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default-receiver'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    continue: true
  - match:
      severity: warning
    receiver: 'warning-alerts'
    continue: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
- name: 'default-receiver'
  # For local development, using file
  webhook_configs:
  - url: 'http://localhost:8080/alert'
    send_resolved: true
  # Uncomment for Slack integration
  # slack_configs:
  # - channel: '#stream-analytics-alerts'
  #   send_resolved: true
  #   title: '{{ template "slack.default.title" . }}'
  #   text: '{{ template "slack.default.text" . }}'
  # Uncomment for email integration
  # email_configs:
  # - to: 'team@example.com'
  #   send_resolved: true

- name: 'critical-alerts'
  # For local development, using file
  webhook_configs:
  - url: 'http://localhost:8080/critical-alert'
    send_resolved: true
  # Uncomment for PagerDuty integration
  # pagerduty_configs:
  # - service_key: 'your-pagerduty-service-key'
  #   send_resolved: true
  # Uncomment for Slack integration
  # slack_configs:
  # - channel: '#stream-analytics-critical'
  #   send_resolved: true
  #   title: '{{ template "slack.default.title" . }}'
  #   text: '{{ template "slack.default.text" . }}'

- name: 'warning-alerts'
  # For local development, using file
  webhook_configs:
  - url: 'http://localhost:8080/warning-alert'
    send_resolved: true
  # Uncomment for Slack integration
  # slack_configs:
  # - channel: '#stream-analytics-warnings'
  #   send_resolved: true
  #   title: '{{ template "slack.default.title" . }}'
  #   text: '{{ template "slack.default.text" . }}' 