global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka monitoring
  - job_name: 'kafka'
    static_configs:
      - targets:
        - 'kafka-exporter:9308'  # Kafka Exporter

  # Spark monitoring
  - job_name: 'spark'
    static_configs:
      - targets:
        - 'spark-master:8080'  # Spark Master metrics
        - 'spark-worker:8081'  # Spark Worker metrics
    metrics_path: /metrics/prometheus

  # Airflow monitoring
  - job_name: 'airflow'
    static_configs:
      - targets:
        - 'airflow-webserver:8080'  # Airflow Webserver
    metrics_path: /metrics
    
  # Data Generator monitoring
  - job_name: 'data-generator'
    static_configs:
      - targets:
        - 'data-generator:8000'  # Custom metrics endpoint
    
  # Spark Processor monitoring
  - job_name: 'spark-processor'
    static_configs:
      - targets:
        - 'spark-processor:8000'  # Custom metrics endpoint

  # PostgreSQL monitoring
  - job_name: 'postgresql'
    static_configs:
      - targets:
        - 'postgres-exporter:9187'  # PostgreSQL exporter
    
  # MinIO monitoring
  - job_name: 'minio'
    static_configs:
      - targets:
        - 'minio:9000'  # MinIO metrics
    metrics_path: /minio/prometheus/metrics

  # Container monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080'
  
  # Node monitoring
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node-exporter:9100' 